* Lessee

Everything marked ~BACKLOG~ is an "if I have time" item.

*NOTE*: Many cities have spaces in the name; normalize with a ~_~.

** DONE Logging (gonna need a clearer picture of that which it is which is up)
** DONE Make lookup requests
** DONE Route for handling lookup
Let's do this.

** DOING A view for displaying results
Needs at minimum to

1. [X] Show the results of the lookup
2. [ ] Either [0/2]
   1. [ ] allow another search right there, or
   2. [ ] link back home

Ideally, given enough time:
1. [X] Format things in a pleasing, human-readable way (not just pprinting EDN)

<2017-12-16 Sat> Well fie. Didn't get to the back/link buttons, I am straight
outta time -- but partly that's because I spent so much dang time making the
results at all readable. Oh well.

** DONE [#A] Check that results are correct
Use [[https://github.com/democracyworks/dw-code-exercise-lein-template/wiki/Current-elections][this wiki page]].

** BACKLOG Augment lookup params sensibly

** BACKLOG Form validation
Ohhhhhboy. Gonna... have to do /something/ with this eventually, I think.
